//
// Created by cleve on 5/12/2022.
//

#ifndef CPPBP_OPTIMIZER_INCLUDE_OPTIMIZER_SGD_OPTIMIZER_H_
#define CPPBP_OPTIMIZER_INCLUDE_OPTIMIZER_SGD_OPTIMIZER_H_

#endif //CPPBP_OPTIMIZER_INCLUDE_OPTIMIZER_SGD_OPTIMIZER_H_
